env: dev
pid: ""
level: 4
log: /dev/stdout

debug:
    addr: 127.0.0.1:12000
    read_timeout: 0s
    write_timeout: 0s
    idle_timeout: 0s
    shutdown_timeout: 0s

http:
    main:
        addr: 127.0.0.1:8080
        read_timeout: 0s
        write_timeout: 0s
        idle_timeout: 0s
        shutdown_timeout: 0s

mysql:
    - name: main
      host: 127.0.0.1
      port: 3306
      schema: test_database
      user: test
      password: test
      maxidleconn: 5
      maxopenconn: 5
      maxconnttl: 50s
      interpolateparams: false
      timezone: UTC
      txisolevel: ""
      charset: utf8mb4,utf8
      timeout: 5s
      readtimeout: 5s
      writetimeout: 5s

sqlite:
    - name: main
      file: ./sqlite.db
      init_migration:
        - ./migration.sql
